(function(){
  'use strict';

  const C=window.BTMCore;
  const $=id=>document.getElementById(id);
  const STORAGE_KEY='btm-laeq-v3-admin-v5';
  const OLD_KEYS=['btm-laeq-v3-admin-v4','btm-laeq-v3-admin-v3'];
  const DAY_ORDER=[1,2,3,4,5,6,0];

  let state=loadState();
  let outputs=(state.outputs?.length?state.outputs:C.templateOutputs(state.templateId||'basic')).map(output=>C.normalizeOutput(output));
  let parsed=null,points=[],acquisitionSeconds=null,results=[];

  function loadState(){
    try{
      const direct=localStorage.getItem(STORAGE_KEY);if(direct)return JSON.parse(direct);
      for(const key of OLD_KEYS){
        const legacy=localStorage.getItem(key);
        if(legacy){
          const migrated=JSON.parse(legacy);
          migrated.outputs=(migrated.outputs||[]).map(output=>({...output,scheduleStart:output.scheduleStart||output.calendarStart||'00:00',scheduleEnd:output.scheduleEnd||output.calendarEnd||'00:00',scheduleDays:output.scheduleDays||output.calendarDays||C.ALL_DAYS,scheduleEnabled:output.mode==='calendar'?true:Boolean(output.scheduleEnabled),scheduleReview:!output.scheduleDays&&!output.calendarDays}));
          return migrated;
        }
      }
    }catch(error){console.warn('Unable to load saved LAeq state',error);}
    return {};
  }

  function persist(){
    state.processingName=$('processingName').value.trim();state.processingActive=$('processingActive').value;state.timeZone=$('timeZone').value;state.templateId=$('templateSelect').value;state.executionMode=$('customExecution').checked?'custom':'smart';state.customFrequency=$('customFrequency').value===''?null:Number($('customFrequency').value);state.customFrequencyUnit=$('customFrequencyUnit').value;state.coverage=Number($('coverage').value)||0;state.catchup=$('catchup').value;state.outputs=outputs;
    try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}catch{}
  }

  function setInitialValues(){
    $('processingName').value=state.processingName||'Environmental noise LAeq';$('processingActive').value=state.processingActive||'yes';$('timeZone').value=state.timeZone||C.getTemplate(state.templateId||'basic')?.timeZone||'Europe/Paris';$('coverage').value=state.coverage??80;$('catchup').value=state.catchup||'yes';$('customFrequency').value=state.customFrequency??'';$('customFrequencyUnit').value=state.customFrequencyUnit||'min';const custom=state.executionMode==='custom';$('customExecution').checked=custom;$('smartExecution').checked=!custom;
  }

  function activatePanel(id){document.querySelectorAll('.tab,.panel').forEach(element=>element.classList.remove('active'));document.querySelector(`.tab[data-panel="${id}"]`)?.classList.add('active');$(id)?.classList.add('active');if(id==='admin')renderAdministration();}
  function daysLabel(days){const normalized=C.normalizeDays(days);if(normalized.length===7)return 'Every day';if(JSON.stringify([...normalized].sort())===JSON.stringify([1,2,3,4,5]))return 'Mon–Fri';if(JSON.stringify([...normalized].sort())===JSON.stringify([1,2,3,4,5,6]))return 'Mon–Sat';return DAY_ORDER.filter(day=>normalized.includes(day)).map(day=>C.DAY_NAMES[day]).join(', ');}
  function scheduleLabel(output){return !output.scheduleEnabled&&output.mode!=='calendar'?'All time':`${output.scheduleStart}–${output.scheduleEnd} · ${daysLabel(output.scheduleDays)}`;}
  function outputSummary(rawOutput){const output=C.normalizeOutput({...rawOutput});if(output.mode==='calendar')return `${C.duration(output.periodSeconds)} scheduled period · ${scheduleLabel(output)} · one result per selected start day`;if(output.mode==='rolling')return `${C.duration(output.periodSeconds)} rolling window · result every ${C.duration(output.stepSeconds)} · ${scheduleLabel(output)}`;return `${C.duration(output.periodSeconds)} fixed window · result every ${C.duration(output.periodSeconds)} · ${scheduleLabel(output)}`;}

  function scheduleEditor(output){
    const dayChips=DAY_ORDER.map(day=>`<label class="day-chip"><input type="checkbox" data-day="${day}" ${output.scheduleDays.includes(day)?'checked':''}><span>${C.DAY_NAMES[day]}</span></label>`).join('');
    return `<div class="schedule-editor"><div class="schedule-time-row"><label class="field"><span>Start</span><input type="time" data-field="scheduleStart" data-lockable value="${C.esc(output.scheduleStart)}"></label><span class="arrow">→</span><label class="field"><span>End</span><input type="time" data-field="scheduleEnd" data-lockable value="${C.esc(output.scheduleEnd)}"></label><div class="derived-period"><span>Calculated period</span><strong>${C.duration(C.nominalScheduleSeconds(output.scheduleStart,output.scheduleEnd))}</strong></div></div><div class="schedule-days" aria-label="Applicable weekdays">${dayChips}</div><div class="schedule-presets"><button type="button" data-days-preset="weekdays">Weekdays</button><button type="button" data-days-preset="mon-sat">Mon–Sat</button><button type="button" data-days-preset="all">Every day</button></div><small>For an overnight period, the selected weekday is the day on which the period starts.</small></div>`;
  }

  function renderOutputs(){
    $('outputList').innerHTML='';
    for(const output of outputs){
      C.normalizeOutput(output);
      const card=document.createElement('article');card.className=`output-card${output.active?'':' inactive'}`;card.dataset.outputId=output.id;
      const windowFields=output.mode==='calendar'?`<div class="field read-only-field"><span>Calculation window</span><strong>${C.duration(output.periodSeconds)}</strong><small>Derived automatically from start and end time.</small></div>`:`<label class="field"><span>Calculation window</span><div class="inline-control"><input type="number" min="1" data-field="duration" data-lockable value="${output.duration}"><select data-field="unit" data-lockable><option value="s" ${output.unit==='s'?'selected':''}>Seconds</option><option value="min" ${output.unit==='min'?'selected':''}>Minutes</option><option value="h" ${output.unit==='h'?'selected':''}>Hours</option></select></div></label>`;
      const rollingFields=output.mode==='rolling'?`<label class="field"><span>Output interval</span><div class="inline-control"><input type="number" min="1" data-field="step" data-lockable value="${output.step}"><select data-field="stepUnit" data-lockable><option value="s" ${output.stepUnit==='s'?'selected':''}>Seconds</option><option value="min" ${output.stepUnit==='min'?'selected':''}>Minutes</option><option value="h" ${output.stepUnit==='h'?'selected':''}>Hours</option></select></div></label>`:`<div class="field read-only-field"><span>Output interval</span><strong>${output.mode==='calendar'?'One per scheduled period':C.duration(output.periodSeconds)}</strong></div>`;
      const scheduleMode=output.mode==='calendar'?`<div class="field read-only-field"><span>Applicable schedule</span><strong>Required for Calendar mode</strong></div>`:`<label class="field"><span>Applicable schedule</span><select data-field="scheduleEnabled" data-lockable><option value="false" ${!output.scheduleEnabled?'selected':''}>All time</option><option value="true" ${output.scheduleEnabled?'selected':''}>Selected hours and days</option></select></label>`;
      card.innerHTML=`<header class="output-card-header"><div><span class="output-status-dot"></span><strong>${C.esc(output.displayName||output.variableName)}</strong><small>${C.esc(output.sourceTemplate?`Template: ${output.sourceTemplate}`:'Custom output')}</small></div><div class="output-card-actions"><label>Active <select data-field="active" aria-label="Output active"><option value="true" ${output.active?'selected':''}>Yes</option><option value="false" ${!output.active?'selected':''}>No</option></select></label><button type="button" class="button danger small" data-remove>Remove</button></div></header><div class="output-card-body"><div class="output-main-grid"><label class="field"><span>Generated variable</span><input data-field="variableName" data-lockable value="${C.esc(output.variableName)}"></label><label class="field"><span>Display name</span><input data-field="displayName" data-lockable value="${C.esc(output.displayName)}"></label><label class="field"><span>Mode</span><select data-field="mode" data-lockable><option value="fixed" ${output.mode==='fixed'?'selected':''}>Fixed</option><option value="rolling" ${output.mode==='rolling'?'selected':''}>Rolling</option><option value="calendar" ${output.mode==='calendar'?'selected':''}>Calendar period</option></select></label>${windowFields}${rollingFields}${scheduleMode}</div>${(output.mode==='calendar'||output.scheduleEnabled)?scheduleEditor(output):''}${output.scheduleReview?'<div class="notice warning compact">This migrated schedule needs review because the former configuration did not store weekdays.</div>':''}<div class="output-summary"><span>Summary</span><strong>${C.esc(outputSummary(output))}</strong></div></div>`;

      card.querySelectorAll('[data-lockable]').forEach(control=>{control.disabled=!output.active;});card.querySelectorAll('[data-day]').forEach(control=>{control.disabled=!output.active;});card.querySelectorAll('[data-days-preset]').forEach(control=>{control.disabled=!output.active;});
      card.querySelectorAll('[data-field]').forEach(control=>control.addEventListener('change',()=>{const field=control.dataset.field;let value=control.value;if(['duration','step'].includes(field))value=Math.max(1,Number(value)||1);if(['active','scheduleEnabled'].includes(field))value=value==='true';output[field]=value;if(field==='mode'){output.scheduleEnabled=value==='calendar'?true:Boolean(output.scheduleEnabled);if(value==='calendar'&&output.scheduleStart===output.scheduleEnd&&output.scheduleStart==='00:00'){output.scheduleStart='07:00';output.scheduleEnd='17:00';}}if(field==='scheduleStart'||field==='scheduleEnd'||field==='mode')output.scheduleReview=false;C.normalizeOutput(output);renderOutputs();updateExecutionUI();persist();}));
      card.querySelectorAll('[data-day]').forEach(control=>control.addEventListener('change',()=>{const selected=[...card.querySelectorAll('[data-day]:checked')].map(item=>Number(item.dataset.day));if(!selected.length){control.checked=true;return;}output.scheduleDays=selected;output.scheduleReview=false;renderOutputs();updateExecutionUI();persist();}));
      card.querySelectorAll('[data-days-preset]').forEach(button=>button.addEventListener('click',()=>{output.scheduleDays=button.dataset.daysPreset==='weekdays'?C.WEEKDAYS.slice():button.dataset.daysPreset==='mon-sat'?C.MON_SAT.slice():C.ALL_DAYS.slice();output.scheduleReview=false;renderOutputs();updateExecutionUI();persist();}));
      card.querySelector('[data-remove]').addEventListener('click',()=>{outputs=outputs.filter(item=>item.id!==output.id);if(state.lastCalculatedByOutput)delete state.lastCalculatedByOutput[output.id];renderOutputs();updateExecutionUI();persist();});
      $('outputList').appendChild(card);
    }
    const activeCount=outputs.filter(output=>output.active).length;$('outputCount').textContent=`${activeCount} active / ${outputs.length} configured`;$('activeOutputCount').textContent=activeCount;
  }

  function renderTemplateOptions(){const templates=C.templateList();$('templateSelect').innerHTML=templates.map(template=>`<option value="${template.id}">${C.esc(template.name)}</option>`).join('');$('templateSelect').value=state.templateId&&C.getTemplate(state.templateId)?state.templateId:'basic';renderTemplateDescription();}
  function renderTemplateDescription(){const template=C.getTemplate($('templateSelect').value);$('templateDescription').innerHTML=template?`<strong>${C.esc(template.description)}</strong><span>Timezone: ${C.esc(template.timeZone)}. ${C.esc(template.note)}</span>`:'';}
  function applySelectedTemplate(){const template=C.getTemplate($('templateSelect').value);if(!template)return;outputs=template.outputs.map(output=>C.normalizeOutput(output));state.templateId=template.id;state.lastCalculatedByOutput={};$('timeZone').value=template.timeZone;results=[];$('resultTable').innerHTML='';$('resultCount').textContent='0';$('runStatus').textContent='Waiting';renderOutputs();updateExecutionUI();persist();}
  function executionMode(){return $('customExecution').checked?'custom':'smart';}
  function customFrequencySeconds(){const value=Number($('customFrequency').value);return Number.isFinite(value)&&value>0?C.seconds(value,$('customFrequencyUnit').value):null;}

  function updateExecutionUI(){
    const recommendation=C.recommendedExecution(outputs,acquisitionSeconds),mode=executionMode(),selectedSeconds=mode==='smart'?recommendation.batchSeconds:customFrequencySeconds();$('smartChoice').classList.toggle('selected',mode==='smart');$('customChoice').classList.toggle('selected',mode==='custom');$('customExecutionPanel').hidden=mode!=='custom';$('recommendedCheck').textContent=recommendation.batchSeconds?C.duration(recommendation.batchSeconds):'—';
    const sourceLabel=acquisitionSeconds?C.duration(acquisitionSeconds):'Not detected',possibleResults=recommendation.batchSeconds?outputs.filter(output=>output.active).reduce((sum,output)=>sum+C.outputsPerRun(output,recommendation.batchSeconds),0):0;
    if(mode==='smart')$('executionSummary').innerHTML=`<div><span>Source acquisition</span><strong>${C.esc(sourceLabel)}</strong></div><div><span>Recommended check interval</span><strong>${recommendation.batchSeconds?`Every ${C.esc(C.duration(recommendation.batchSeconds))}`:'No active output'}</strong></div><div><span>Results per execution</span><strong>Up to ${possibleResults}</strong></div><p>BTM waits until at least one configured period is complete, then calculates all pending results in one execution.</p>`;
    else if(selectedSeconds)$('executionSummary').innerHTML=`<div><span>Source acquisition</span><strong>${C.esc(sourceLabel)}</strong></div><div><span>Custom run</span><strong>Every ${C.esc(C.duration(selectedSeconds))}</strong></div><div><span>Estimated checks</span><strong>About ${Math.ceil(86400/selectedSeconds).toLocaleString()}/day</strong></div><p>Each check reads the latest database timestamp. If no complete period is available, it is skipped.</p>`;
    else $('executionSummary').innerHTML=`<div><span>Source acquisition</span><strong>${C.esc(sourceLabel)}</strong></div><div><span>Recommended check</span><strong>${C.esc(C.duration(recommendation.batchSeconds))}</strong></div><div><span>Custom schedule</span><strong>Not configured</strong></div><p>Enter a custom interval before saving.</p>`;
    const warnings=[...(recommendation.warnings||[])];if(mode==='custom'){if(!selectedSeconds)warnings.unshift('Enter a custom run interval. No value is proposed automatically.');else if(recommendation.batchSeconds&&selectedSeconds<recommendation.batchSeconds)warnings.push(`This schedule checks approximately ${Math.ceil(recommendation.batchSeconds/selectedSeconds)} times more often than the recommended interval.`);}
    $('executionWarning').innerHTML=warnings.length?`<div class="notice warning">${warnings.map(C.esc).join('<br>')}</div>`:'<div class="notice success">The execution configuration is consistent with the active calculation windows.</div>';renderAdministration();
  }

  function validateConfiguration(){const active=outputs.filter(output=>output.active);if(!active.length)return 'At least one LAeq output must be active.';const names=active.map(output=>output.variableName.trim());if(names.some(name=>!name))return 'Every active output needs a generated variable name.';if(new Set(names).size!==names.length)return 'Generated variable names must be unique.';for(const output of active){C.normalizeOutput(output);if(output.periodSeconds<=0)return `${output.displayName}: calculation window must be greater than zero.`;if((output.mode==='calendar'||output.scheduleEnabled)&&!C.normalizeDays(output.scheduleDays).length)return `${output.displayName}: select at least one weekday.`;if(output.mode==='rolling'&&output.stepSeconds<=0)return `${output.displayName}: output interval must be greater than zero.`;}if(executionMode()==='custom'&&!customFrequencySeconds())return 'Enter a valid custom execution interval.';return null;}
  function currentVariableName(){return parsed?$('valueColumn').selectedOptions[0]?.textContent||'—':'—';}
  function refreshSource(){if(!parsed)return;points=C.makePoints(parsed,$('timestampColumn').value,$('valueColumn').value,$('timeZone').value);acquisitionSeconds=C.inferAcquisition(points);$('sourceStatus').className='notice info';$('sourceStatus').innerHTML=`<strong>Selected variable:</strong> ${C.esc(currentVariableName())} · <strong>Format:</strong> ${C.esc(parsed.format)} · <strong>Estimated acquisition:</strong> ${C.duration(acquisitionSeconds)}.`;$('sourcePreview').innerHTML=points.slice(0,8).map(point=>`<tr><td>${C.fmt(point.t,$('timeZone').value)}</td><td>${point.v}</td></tr>`).join('');$('sourceRows').textContent=parsed.rows.length;$('validRows').textContent=points.length;$('acquisition').textContent=C.duration(acquisitionSeconds);updateExecutionUI();}
  function loadSelectedFile(file){if(!file)return;const reader=new FileReader();reader.onload=()=>{try{parsed=C.parseSource(reader.result,file.name);$('fileName').textContent=file.name;$('detectedFormat').value=parsed.format;const options=parsed.columns.map(column=>`<option value="${column.index}">${C.esc(column.name)}</option>`).join('');$('timestampColumn').innerHTML=options;$('valueColumn').innerHTML=options;$('timestampColumn').value=parsed.timeIndex;$('valueColumn').value=parsed.valueIndex;refreshSource();}catch(error){$('sourceStatus').className='notice warning';$('sourceStatus').textContent=error.message;}};reader.readAsText(file,'ISO-8859-1');}

  function runProcessing(trigger='Manual run'){
    const validation=validateConfiguration();if(validation){$('runMessage').className='notice warning';$('runMessage').textContent=validation;return;}if(!points.length||!acquisitionSeconds){$('runMessage').className='notice warning';$('runMessage').textContent='Load valid source data first.';return;}
    const useCatchup=$('manualCatchup').checked&&$('catchup').value==='yes';results=C.calculateAll(points,outputs,acquisitionSeconds,{validCoverage:Number($('coverage').value)||0,timestampConvention:parsed.timestampConvention,timeZone:$('timeZone').value,lastCalculatedByOutput:useCatchup?(state.lastCalculatedByOutput||{}):{}});const timeZone=$('timeZone').value;
    $('resultTable').innerHTML=results.map(result=>`<tr><td>${C.esc(result.variableName)}</td><td>${C.esc(result.mode)}</td><td>${C.fmt(result.timestamp,timeZone)}</td><td>${C.fmt(result.start,timeZone)}</td><td>${C.fmt(result.end,timeZone)}</td><td><strong>${result.value.toFixed(2)}</strong></td><td>${result.samples}</td><td>${result.expected}</td><td>${Math.min(100,result.coverage).toFixed(1)}%</td><td><span class="pill ${result.status==='Catch-up'?'info':''}">${result.status}</span></td></tr>`).join('');
    const skipped=results.length===0;$('resultCount').textContent=results.length;$('runStatus').textContent=skipped?'Skipped':'Success';$('downloadResults').disabled=skipped;$('runMessage').className=`notice ${skipped?'info':'success'}`;$('runMessage').textContent=skipped?'Skipped — No new complete period available.':`${results.length} result(s) generated across ${new Set(results.map(result=>result.outputId)).size} output(s).`;
    state.lastCalculatedByOutput||={};for(const output of outputs){const outputResults=results.filter(result=>result.outputId===output.id);if(outputResults.length)state.lastCalculatedByOutput[output.id]=Math.max(...outputResults.map(result=>result.end));}
    state.lastExecution=Date.now();state.lastStatus=skipped?'Skipped':'Success';state.history||=[];state.history.unshift({timestamp:state.lastExecution,trigger,status:state.lastStatus,resultCount:results.length,outputCount:outputs.filter(output=>output.active).length,comment:skipped?'No new complete period available':'Calculation completed'});state.history=state.history.slice(0,30);persist();renderAdministration();
  }

  function executionLabel(){const recommendation=C.recommendedExecution(outputs,acquisitionSeconds);if(executionMode()==='smart')return recommendation.batchSeconds?`Smart · every ${C.duration(recommendation.batchSeconds)}`:'Smart · waiting for outputs';const custom=customFrequencySeconds();return custom?`Custom · every ${C.duration(custom)}`:'Custom · incomplete';}
  function renderAdministration(){if(!$('processingList'))return;const status=$('processingActive').value==='no'?'Inactive':state.lastStatus||'Not executed';$('processingList').innerHTML=`<tr><td><strong>${C.esc($('processingName').value||'Untitled')}</strong></td><td>${C.esc(currentVariableName())}</td><td>${outputs.filter(output=>output.active).length} active / ${outputs.length}</td><td>${C.esc($('timeZone').value)}</td><td>${C.esc(executionLabel())}</td><td><span class="pill ${/Inactive|Skipped|Not/.test(status)?'wait':''}">${C.esc(status)}</span></td><td><button class="button small" id="editProcessing">Edit</button></td></tr>`;$('editProcessing').addEventListener('click',showDetails);}
  function showDetails(){const details=$('processingDetails');details.hidden=false;const timeZone=$('timeZone').value,outputRows=outputs.map(output=>{C.normalizeOutput(output);const last=state.lastCalculatedByOutput?.[output.id];return `<tr><td><strong>${C.esc(output.variableName)}</strong></td><td>${C.esc(outputSummary(output))}</td><td>${last?C.fmt(last,timeZone):'Never'}</td><td><span class="pill ${output.active?'':'wait'}">${output.active?'Active':'Inactive'}</span></td></tr>`;}).join(''),historyRows=(state.history||[]).map(item=>`<tr><td>${new Date(item.timestamp).toLocaleString()}</td><td>${C.esc(item.trigger)}</td><td>${item.resultCount}</td><td><span class="pill ${item.status==='Skipped'?'wait':''}">${C.esc(item.status)}</span></td><td>${C.esc(item.comment)}</td></tr>`).join('')||'<tr><td colspan="5">No execution yet.</td></tr>';
    details.innerHTML=`<div class="details-header"><div><h3>${C.esc($('processingName').value)}</h3><p>${C.esc($('timeZone').value)} · ${C.esc(executionLabel())}</p></div><div><button class="button small" id="editOutputs">Edit outputs</button> <button class="button small warning-button" id="manualFromAdmin">Manual run</button> <button class="button small" id="closeDetails">Close</button></div></div><h3>Generated variables</h3><div class="table-wrap"><table><thead><tr><th>Variable</th><th>Calculation</th><th>Last calculated end</th><th>Status</th></tr></thead><tbody>${outputRows}</tbody></table></div><h3>Execution history</h3><div class="table-wrap"><table><thead><tr><th>Time</th><th>Trigger</th><th>Results</th><th>Status</th><th>Comment</th></tr></thead><tbody>${historyRows}</tbody></table></div>`;$('editOutputs').addEventListener('click',()=>activatePanel('outputs'));$('manualFromAdmin').addEventListener('click',()=>activatePanel('manual'));$('closeDetails').addEventListener('click',()=>{details.hidden=true;});
  }
  function downloadResults(){const timeZone=$('timeZone').value,header='variable,mode,timestamp,start,end,LAeq_dBA,samples,expected,coverage,type',body=results.map(result=>[result.variableName,result.mode,C.fmt(result.timestamp,timeZone),C.fmt(result.start,timeZone),C.fmt(result.end,timeZone),result.value.toFixed(3),result.samples,result.expected,result.coverage.toFixed(2),result.status].join(',')),link=document.createElement('a');link.href=URL.createObjectURL(new Blob([[header,...body].join('\n')],{type:'text/csv'}));link.download='btm_laeq_results.csv';link.click();URL.revokeObjectURL(link.href);}

  function bindEvents(){
    document.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>activatePanel(tab.dataset.panel)));$('templateSelect').addEventListener('change',renderTemplateDescription);$('applyTemplate').addEventListener('click',applySelectedTemplate);
    $('addOutput').addEventListener('click',()=>{outputs.push(C.normalizeOutput({id:`custom-${Date.now()}`,variableName:'Noise_LAeq_custom',displayName:'Custom LAeq',mode:'fixed',duration:30,unit:'min',step:30,stepUnit:'min',scheduleEnabled:false,scheduleStart:'07:00',scheduleEnd:'19:00',scheduleDays:C.ALL_DAYS.slice(),active:true}));state.templateId='basic';renderOutputs();updateExecutionUI();persist();});
    $('sourceFile').addEventListener('change',event=>loadSelectedFile(event.target.files[0]));const upload=document.querySelector('.upload-zone');['dragenter','dragover'].forEach(type=>upload.addEventListener(type,event=>{event.preventDefault();upload.classList.add('dragging');}));['dragleave','drop'].forEach(type=>upload.addEventListener(type,event=>{event.preventDefault();upload.classList.remove('dragging');}));upload.addEventListener('drop',event=>loadSelectedFile(event.dataTransfer.files[0]));$('timestampColumn').addEventListener('change',refreshSource);$('valueColumn').addEventListener('change',refreshSource);
    ['smartExecution','customExecution','customFrequency','customFrequencyUnit','coverage','catchup','processingActive','processingName','timeZone'].forEach(id=>{$(id).addEventListener(['customFrequency','processingName'].includes(id)?'input':'change',()=>{if(id==='timeZone'&&points.length)refreshSource();updateExecutionUI();persist();});});
    $('runNow').addEventListener('click',()=>runProcessing());$('downloadResults').addEventListener('click',downloadResults);
    $('saveProcessing').addEventListener('click',()=>{const validation=validateConfiguration();if(validation){activatePanel(validation.includes('execution')?'execution':'outputs');if(validation.includes('execution'))$('executionWarning').innerHTML=`<div class="notice warning">${C.esc(validation)}</div>`;else window.alert(validation);return;}persist();activatePanel('admin');showDetails();});
    $('resetApp').addEventListener('click',()=>{if(window.confirm('Reset the LAeq processing configuration and calculation state?')){localStorage.removeItem(STORAGE_KEY);location.reload();}});
  }

  setInitialValues();renderTemplateOptions();bindEvents();renderOutputs();updateExecutionUI();renderAdministration();
})();
